
    
    
backend_homepage:
    path:     /homepage
    defaults: { _controller: backendBundle:Home:index }
    
backend_blog_homepage:
    path:     /blog/index
    defaults: { _controller: backendBundle:Blog:index }
    
backend_crearPublicacion_homepage:
    path:     /blog/crearPublicacion
    defaults: { _controller: backendBundle:Blog:crearPublicacion }

backend_crearPublicacion_ejecutar:
    path:     /blog/crearPublicacion/ejecutar
    defaults: { _controller: backendBundle:Blog:crearPublicacionEjecutar }